[package]
name = "rootcause-extras"
version = "0.12.1"
edition = "2024"

[dependencies]
# Internal dependencies
rootcause = { path = "../", version = "=0.12.1" }
rootcause-backtrace = { path = "../rootcause-backtrace", version = "=0.12.1" }

serde.version = "1"
serde.optional = true
serde.features = ["derive"]

serde_json.version = "1"
serde_json.optional = true
serde_json.features = ["preserve_order"]

[features]
default = ["json"]
json = ["dep:serde", "dep:serde_json"]